// Datos del equipo Agenda Territorial — Convenio 1022 de 2025
// Bitácora interna · Despacho · Ministerio de las Culturas, las Artes y los Saberes

const TEAM = [
  {
    id: 'yuli',
    nombre: 'Yuli Rocío Camelo',
    corto: 'Yuli',
    rol: 'Coordinación general',
    area: 'Coordinación',
    color: '#5A3680',
    inicial: 'Y',
    descripcion: 'Articula con Dirección de Poblaciones y con la institucionalidad. Decide rumbo y prioridades del Convenio.',
  },
  {
    id: 'monica',
    nombre: 'Mónica Andrea López',
    corto: 'Mónica',
    rol: 'Coordinación de campo',
    area: 'Coordinación',
    color: '#3D50A8',
    inicial: 'M',
    descripcion: 'Articula el documento conceptual del Encuentro RIJ y el trabajo territorial con organizaciones.',
  },
  {
    id: 'jeimmy',
    nombre: 'Jeimmy Ruiz',
    corto: 'Jeimmy',
    rol: 'Orientadora — Red Intercultural Juvenil',
    area: 'Red Intercultural Juvenil',
    color: '#D97B3F',
    inicial: 'J',
    descripcion: 'Acompaña a las organizaciones de la RIJ. Lleva CONPES Juventudes y articulación con poblaciones.',
  },
  {
    id: 'mercy',
    nombre: 'Mercy Tatiana Arias',
    corto: 'Mercy',
    rol: 'Orientadora — Red de Mujeres Sabedoras, Creadoras y Gestoras',
    area: 'Red de Mujeres',
    color: '#A8438A',
    inicial: 'M',
    descripcion: 'Acompaña a las mujeres sabedoras y gestoras. Lidera socializaciones de costos y firma de contratos.',
  },
  {
    id: 'emerson',
    nombre: 'Emerson Fandiño',
    corto: 'Emerson',
    rol: 'Seguimiento documental',
    area: 'Seguimiento',
    color: '#528E71',
    inicial: 'E',
    descripcion: 'Convoca reuniones, maneja agenda del equipo, base de datos y caracterización del Directorio Vivo.',
  },
  {
    id: 'felipe',
    nombre: 'Felipe Camacho Otero',
    corto: 'Felipe',
    rol: 'Enlace de comunicaciones',
    area: 'Comunicaciones',
    color: '#E8C535',
    inicial: 'F',
    descripcion: 'Diseña piezas, manuales de identidad, plataforma web y el Ciclo de Formación Puente.',
  },
];

// Formato fecha: año-mes-día (ISO). Mes 04=abril, 05=mayo, 06=junio, 07=julio.
// Fecha de hoy en ISO local (yyyy-mm-dd) — usa hora local del dispositivo,
// NO Date.toISOString() que devuelve UTC y puede retrasarse un día en Colombia (UTC-5).
const _hoy = new Date();
const HOY_ISO = `${_hoy.getFullYear()}-${String(_hoy.getMonth() + 1).padStart(2, '0')}-${String(_hoy.getDate()).padStart(2, '0')}`;

const CRONOGRAMA = [
  {
    id: 't-may05-a',
    fecha: '2026-05-05', hora: '12:00 m.',
    titulo: 'Reunión con Andrea — Fondo Mixto',
    detalle: 'Aclarar cláusula que vincula a las dos organizaciones aliadas y cláusula octava de derechos de autor.',
    responsables: ['emerson', 'mercy', 'jeimmy', 'yuli'],
    tipo: 'reunion', estado: 'hecha',
  },
  {
    id: 't-may05-b',
    fecha: '2026-05-05',
    titulo: 'Firma de contratos · Ciclo de Formación Puente',
    detalle: 'Ajuste a 5 sesiones por orientadora.',
    responsables: ['mercy', 'jeimmy'],
    tipo: 'entrega', estado: 'hecha',
  },
  {
    id: 't-may06-a',
    fecha: '2026-05-06',
    titulo: 'Documento borrador CONPES Juventudes',
    detalle: 'Remitir a Yuli y Mónica para revisión.',
    responsables: ['jeimmy'],
    tipo: 'entrega', estado: 'hecha',
  },
  {
    id: 't-may06-b',
    fecha: '2026-05-06',
    titulo: 'Listado de organizaciones con ubicación',
    detalle: 'Caracterización del Directorio Vivo para costeo de transportes.',
    responsables: ['felipe', 'jeimmy', 'emerson'],
    tipo: 'entrega', estado: 'hecha',
  },
  {
    id: 't-sem19-a',
    fecha: '2026-05-08', semanaInicio: '2026-05-05', semanaFin: '2026-05-09',
    titulo: 'Articulación con Dirección de Poblaciones',
    detalle: 'Reunión con Mercy y gestión con Alejandra (línea gráfica encuentro de mujeres).',
    responsables: ['yuli', 'monica'],
    tipo: 'gestion', estado: 'pendiente', semana: true,
  },
  {
    id: 't-sem19-b',
    fecha: '2026-05-08', semanaInicio: '2026-05-05', semanaFin: '2026-05-09',
    titulo: 'Gestión British Council',
    detalle: 'Definir canal de solicitud por Oficina de Internacionales.',
    responsables: ['yuli', 'jeimmy'],
    tipo: 'gestion', estado: 'pendiente', semana: true,
  },
  {
    id: 't-sem19-c',
    fecha: '2026-05-08', semanaInicio: '2026-05-05', semanaFin: '2026-05-09',
    titulo: 'Intercambio de bases de datos con poblaciones',
    detalle: 'Para convocatoria del Ciclo de Formación e instructivo.',
    responsables: ['mercy', 'emerson'],
    tipo: 'gestion', estado: 'pendiente', semana: true,
  },
  {
    id: 't-may08-ciclo',
    fecha: '2026-05-08',
    titulo: 'Reunión Ciclo de Formación Puente · calendario en firme ✓',
    detalle: 'Mercy, Jeimmy y Felipe cerraron el calendario definitivo: 12 sesiones con fechas, horas y títulos exactos. Horarios: lun/mar 18:30–20:00 · vie 17:30–19:00 · festivos → martes 10:00–11:30.',
    responsables: ['felipe', 'mercy', 'jeimmy'],
    tipo: 'reunion', estado: 'hecha',
  },
  // — Compromisos del acta del 8 de mayo ·····················································
  {
    id: 't-may08-c2',
    fecha: '2026-05-08',
    titulo: 'Compartir enlace Canva de la presentación con Mercy y Jeimmy',
    detalle: 'Felipe comparte el enlace de edición de la presentación «Ciclo de Formación Puente» en Canva para que Mercy y Jeimmy puedan modificarla.',
    responsables: ['felipe'],
    tipo: 'entrega', estado: 'pendiente',
  },
  {
    id: 't-may08-c3',
    fecha: '2026-05-08',
    titulo: 'Enviar documento de contenidos Comunicaciones I y II',
    detalle: 'Felipe envía a Mercy y Jeimmy el documento que detalla el contenido de las sesiones del 15 y 22 de mayo.',
    responsables: ['felipe'],
    tipo: 'entrega', estado: 'pendiente',
  },
  {
    id: 't-may09-c4',
    fecha: '2026-05-09',
    titulo: 'Carta de compromiso institucional · versión depurada',
    detalle: 'Felipe redacta y envía al equipo la carta de compromiso para las organizaciones. Versión más corta que el borrador de Claudia. Las organizaciones la devuelven firmada después de la presentación del 11 de mayo.',
    responsables: ['felipe'],
    tipo: 'entrega', estado: 'hecha',
  },
  {
    id: 't-may09-c5',
    fecha: '2026-05-09',
    titulo: 'Correo de invitación a organizaciones · presentación del 11 de mayo',
    detalle: 'Felipe (con apoyo de M.) envía invitación por correo a todas las organizaciones para la sesión inaugural del Ciclo del 11 de mayo, 18:00–19:30. Con copia a agenda territorial. Sin pieza gráfica en esta convocatoria.',
    responsables: ['felipe'],
    tipo: 'entrega', estado: 'hecha',
  },
  {
    id: 't-may09-c1',
    fecha: '2026-05-09',
    titulo: 'Presentación Canva «Ciclo de Formación Puente» · depuración',
    detalle: 'Mercy y Jeimmy limpian la presentación duplicada en Canva: ajustan diapositiva de enfoques y arman la diapositiva de acuerdos/reglas del juego (no existe aún). Confirman al equipo que pudieron abrir y modificar.',
    responsables: ['mercy', 'jeimmy'],
    tipo: 'entrega', estado: 'pendiente',
    alerta: 'Cierra domingo 10',
  },
  {
    id: 't-may11-c6',
    fecha: '2026-05-11',
    titulo: 'Correo a organizaciones en latencia · ingreso al Ciclo',
    detalle: 'Jeimmy envía correo previo al 11 de mayo a las organizaciones en estado de latencia/alerta de la ruta de desarrollo de capacidades, para informarles que necesitan ingresar al proceso.',
    responsables: ['jeimmy'],
    tipo: 'entrega', estado: 'pendiente',
  },
  {
    id: 't-may11-c7',
    fecha: '2026-05-11',
    titulo: 'Gestión con Fondo Mixto · certificación del Ciclo',
    detalle: 'Yuli precisa con el gerente del Fondo Mixto (Dr. Juan Carlos) la emisión del certificado oficial de las sesiones del Ciclo, antes de la presentación inaugural.',
    responsables: ['yuli'],
    tipo: 'gestion', estado: 'pendiente',
    alerta: 'Gestión prioritaria',
  },
  {
    id: 't-may11-c9',
    fecha: '2026-05-11',
    titulo: 'Agregar a Felipe a grupo Minga Nodo Andina',
    detalle: 'Jeimmy incorpora a Felipe Camacho al grupo de la Minga del Nodo Andina para el ejercicio de identidad por nodos. A partir del 11 de mayo inician tres puntos de trabajo en mayo.',
    responsables: ['jeimmy'],
    tipo: 'gestion', estado: 'pendiente',
  },
  {
    id: 't-may11-sesion0',
    fecha: '2026-05-11', hora: '18:00–19:30',
    titulo: 'Sesión inaugural · Presentación del Ciclo de Formación Puente',
    detalle: 'Con todas las organizaciones del Convenio 1022. Estructura: (i) contexto del convenio — Yuli/Mónica 5–10 min; (ii) apertura del Ciclo — Jeimmy 10 min; (iii) cronograma 12 sesiones — Felipe; (iv) reglas del juego — Mercy 15 min; (v) preguntas — 20 min. Total: ~90 min.',
    responsables: ['yuli', 'monica', 'jeimmy', 'mercy', 'felipe'],
    tipo: 'formacion', estado: 'pendiente',
    alerta: 'Sesión inaugural',
  },
  {
    id: 't-indef-c8',
    fecha: '2026-05-11',
    titulo: 'Continuidad Red de Mujeres en el Convenio · decisión pendiente',
    detalle: 'Mercy comunica al equipo, cuando tenga claridad, la decisión sobre si la Red de Mujeres continúa en Artes para la Paz o se vincula a Poblaciones. Mientras tanto, las cinco mujeres quedan invitadas a participar en sesiones de comunicaciones del nodo RIJ.',
    responsables: ['mercy'],
    tipo: 'decision', estado: 'pendiente',
  },
  {
    id: 't-may08',
    fecha: '2026-05-08',
    titulo: 'Sede del Encuentro RIJ · confirmada Cali ✓',
    detalle: 'Yuli Camelo confirmó al cierre del día: el Encuentro de la RIJ será en Cali. Decisión comunicada a todo el equipo el 8 de mayo de 2026.',
    responsables: ['yuli'],
    tipo: 'decision', estado: 'hecha',
  },
  {
    id: 't-may13-ciclo',
    fecha: '2026-05-13',
    titulo: 'Inicio del Ciclo · Finanzas Personales',
    detalle: 'Sesión 1 con Mercy. Arranca el Ciclo de Formación Puente.',
    responsables: ['mercy'],
    tipo: 'formacion', estado: 'pendiente',
  },
  {
    id: 't-may15-ciclo',
    fecha: '2026-05-15',
    titulo: 'Ciclo · Comunicaciones I',
    detalle: 'Sesión 2 con Felipe.',
    responsables: ['felipe'],
    tipo: 'formacion', estado: 'pendiente',
  },
  {
    id: 't-may08',
    fecha: '2026-05-08',
    titulo: 'Sede del Encuentro RIJ · confirmada Cali ✓',
    detalle: 'Yuli Camelo confirmó al cierre del día: el Encuentro de la RIJ será en Cali. Decisión comunicada a todo el equipo el 8 de mayo de 2026.',
    responsables: ['yuli'],
    tipo: 'decision', estado: 'hecha',
  },
  {
    id: 't-may11-a',
    fecha: '2026-05-11', hora: '8:00 a 9:00 a.m.',
    titulo: 'Reunión semanal del equipo',
    detalle: 'Primer encuentro de seguimiento. A partir de aquí, todos los lunes.',
    responsables: ['yuli', 'monica', 'jeimmy', 'mercy', 'emerson', 'felipe'],
    tipo: 'reunion', estado: 'pendiente',
    recurrente: 'Cada lunes',
  },
  {
    id: 't-may11-b',
    fecha: '2026-05-11', hora: '6:00 p.m.',
    titulo: 'Socialización Ciclo de Formación Puente',
    detalle: 'Con todas las organizaciones del Convenio 1022.',
    responsables: ['mercy', 'jeimmy', 'felipe'],
    tipo: 'reunion', estado: 'pendiente',
  },
  {
    id: 't-sem20',
    fecha: '2026-05-13', semanaInicio: '2026-05-11', semanaFin: '2026-05-15',
    titulo: 'Cierre virtual de la vigencia 2025',
    detalle: 'Espacio de 2 horas para revisar avances, cierres y alertas.',
    responsables: ['yuli', 'monica', 'jeimmy', 'mercy', 'emerson', 'felipe'],
    tipo: 'reunion', estado: 'pendiente', semana: true,
  },
  {
    id: 't-may15',
    fecha: '2026-05-15',
    titulo: 'Primer borrador del documento conceptual — Encuentro RIJ',
    detalle: 'Mónica articula. Aporta todo el equipo.',
    responsables: ['monica', 'jeimmy', 'mercy', 'felipe', 'yuli'],
    tipo: 'entrega', estado: 'pendiente',
    alerta: 'Entrega borrador',
  },
  {
    id: 't-may19',
    fecha: '2026-05-19', hora: '6:00 p.m.',
    titulo: 'Socialización del instructivo de costos y gastos',
    detalle: 'Asistencia obligatoria del responsable contable o financiero de cada organización. Sesión grabada.',
    responsables: ['mercy', 'jeimmy', 'felipe', 'emerson'],
    tipo: 'reunion', estado: 'pendiente',
  },
  {
    id: 't-may25',
    fecha: '2026-05-25',
    titulo: 'Documento conceptual consolidado — Encuentro RIJ',
    detalle: 'Versión revisada y lista para diagramación con Felipe.',
    responsables: ['monica', 'jeimmy', 'mercy', 'felipe'],
    tipo: 'entrega', estado: 'pendiente',
    alerta: 'Documento consolidado',
  },
  {
    id: 't-jun24',
    fecha: '2026-06-24', semanaInicio: '2026-06-24', semanaFin: '2026-06-27',
    titulo: 'Encuentro Red Intercultural Juvenil · Cali',
    detalle: '3 noches · 5 jornadas efectivas · ~50 participantes · sede: Cali. Llegada 24 jun, salida 27 jun.',
    responsables: ['yuli', 'monica', 'jeimmy', 'mercy', 'emerson', 'felipe'],
    tipo: 'encuentro', estado: 'pendiente', destacado: true,
  },
  {
    id: 't-may11-catering',
    fecha: '2026-05-11',
    titulo: 'Gestión de alimentación y apoyos · Encuentro RIJ',
    detalle: 'Yuli gestiona apoyo del British Council. Emerson cotiza alimentación para 50 personas con el proveedor de Cali.',
    responsables: ['yuli', 'emerson'],
    tipo: 'gestion', estado: 'pendiente',
  },
  {
    id: 't-may11-hiphop',
    fecha: '2026-05-11',
    titulo: 'Invitación a Red de Hip Hop como información abierta',
    detalle: 'Emerson envía la pieza gráfica de la sesión inaugural al grupo de WhatsApp de la Red de Hip Hop, sin compromiso frente a su continuidad.',
    responsables: ['emerson'],
    tipo: 'entrega', estado: 'pendiente',
  },
  {
    id: 't-may11-agenda',
    fecha: '2026-05-11',
    titulo: 'Borrador agenda metodológica sesión inaugural',
    detalle: 'Felipe comparte con Mónica y Yuli el borrador tras concretarlo con Mercy y Jeimmy.',
    responsables: ['felipe'],
    tipo: 'entrega', estado: 'pendiente',
  },
  {
    id: 't-jun24-grafica',
    fecha: '2026-06-24',
    titulo: 'Producción gráfica y branding · Encuentro RIJ',
    detalle: 'Felipe coordina propuesta de screen stencil/estampado, asegura branding de la agenda y avanza en posible diseño de camiseta.',
    responsables: ['felipe'],
    tipo: 'entrega', estado: 'pendiente',
  },
  {
    id: 't-jun24-conpes',
    fecha: '2026-06-24',
    titulo: 'Articulación día CONPES en Encuentro RIJ',
    detalle: 'Jeimmy define el día específico. Yuli solicita a Poblaciones presencia de delegado y viáticos.',
    responsables: ['jeimmy', 'yuli'],
    tipo: 'gestion', estado: 'pendiente',
  },
  {
    id: 't-jun24-vuelos',
    fecha: '2026-06-24',
    titulo: 'Vuelos y acomodación · Encuentro RIJ',
    detalle: 'Emerson cuadra vuelos (llegada 24 jun tarde, salida 27 jun tarde). Equipo anuncia acomodación doble a organizaciones.',
    responsables: ['emerson', 'yuli', 'monica', 'jeimmy', 'mercy', 'felipe'],
    tipo: 'gestion', estado: 'pendiente',
  },
];

// Ciclo de Formación Puente · Avanzada formativa
// Calendario definitivo cerrado en reunión del 8 de mayo con Mercy Arias, Jeimmy Ruiz y Felipe Camacho
// Horarios: lun/mar 18:30–20:00 · vie 17:30–19:00 · si lunes es festivo → martes 10:00–11:30
const CICLO = [
  { n: 0,  fecha: '2026-05-11', dia: 'Lunes',     hora: '18:00–19:30', orient: 'yuli',   tipo: 'Sesión inaugural',    tema: 'Presentación del Ciclo de Formación Puente',               estado: 'hecha', estadoCal: 'confirmado', alerta: 'Sesión inaugural — abre el calendario', enlaceSesion: '', enlaceGrabacion: 'https://mcultura-my.sharepoint.com/:v:/g/personal/agendaterritorial_mincultura_gov_co/IQCPShs62TXaRpKQdLb6LU_cAeK5zyjPX3HisJu1AKNbTag?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=aiepQp', enlaceCompromiso: 'compromiso.html' },
  { n: 1,  fecha: '2026-05-13', dia: 'Miércoles', hora: '18:30–20:00', orient: 'mercy',  tipo: 'Saberes financieros', tema: 'Finanzas personales',                                       estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: 'https://mcultura-my.sharepoint.com/:v:/g/personal/agendaterritorial_mincultura_gov_co/IQDRTTKUfhzsQIJGYKxtS-EeAeakfJdJjbsb7CrFUNk0oCM?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=Xuk9NS', enlacePuntoControl: 'https://forms.cloud.microsoft/r/QwYNBHySrK?origin=lprLink' },
  { n: 2,  fecha: '2026-05-15', dia: 'Viernes',   hora: '17:30–19:00', orient: 'felipe', tipo: 'Comunicaciones',       tema: 'Desde dónde hablamos — Comunicaciones 1',                 estado: 'hecha', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: 'https://mcultura-my.sharepoint.com/:v:/g/personal/agendaterritorial_mincultura_gov_co/IQBpEV526p76TrPw036-cSEnAdhb41EGjOIj3zpDWbFDzXs?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=qCLX8i', enlacePuntoControl: 'https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=Tovyk1yTFEyIrOSGl8H8l52n7vNaiztOlUJsivIhn2FUNFJBTjNaWjQ3UDVFRTlMSDFMUVRKNUJHVy4u' },
  { n: 3,  fecha: '2026-05-19', dia: 'Martes',    hora: '10:00–11:30', orient: 'jeimmy', tipo: 'Saberes RIJ',          tema: 'Contexto: curar el entorno',                              estado: 'pendiente', estadoCal: 'confirmado', alerta: 'Lunes 18 festivo → martes 10:00', enlaceSesion: 'https://teams.microsoft.com/meet/291243503532646?p=bwfIPAWe43MO6N300f', enlaceGrabacion: '' },
  { n: 4,  fecha: '2026-05-20', dia: 'Miércoles', hora: '18:30–20:00', orient: 'mercy',  tipo: 'Saberes financieros', tema: 'Presupuesto',                                               estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 5,  fecha: '2026-05-22', dia: 'Viernes',   hora: '17:30–19:00', orient: 'felipe', tipo: 'Comunicaciones',       tema: 'Decidir qué se dice y qué se cuida — Comunicaciones 2',   estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 6,  fecha: '2026-05-25', dia: 'Lunes',     hora: '18:30–20:00', orient: 'jeimmy', tipo: 'Saberes RIJ',          tema: 'Reciprocidad: la ética de la corresponsabilidad',          estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 7,  fecha: '2026-05-27', dia: 'Miércoles', hora: '18:30–20:00', orient: 'mercy',  tipo: 'Saberes financieros', tema: 'Flujo de caja',                                             estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 8,  fecha: '2026-05-29', dia: 'Viernes',   hora: '17:30–19:00', orient: 'mercy',  tipo: 'Saberes financieros', tema: 'Diversificación de ingresos',                               estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 9,  fecha: '2026-06-01', dia: 'Lunes',     hora: '18:30–20:00', orient: 'jeimmy', tipo: 'Saberes RIJ',          tema: 'Flujo del ser: la coherencia interna',                     estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 10, fecha: '2026-06-03', dia: 'Miércoles', hora: '18:30–20:00', orient: 'mercy',  tipo: 'Saberes financieros', tema: 'Indicadores para el control financiero',                    estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 11, fecha: '2026-06-05', dia: 'Viernes',   hora: '17:30–19:00', orient: 'jeimmy', tipo: 'Saberes RIJ',          tema: 'Caja de herramientas 1: lo político del cuidado situado',  estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
  { n: 12, fecha: '2026-06-22', dia: 'Lunes',     hora: '18:30–20:00', orient: 'jeimmy', tipo: 'Saberes RIJ',          tema: 'Herramientas 2: lo político del cuidado situado',          estado: 'pendiente', estadoCal: 'confirmado', enlaceSesion: '', enlaceGrabacion: '' },
];

// Hilo del ciclo · proceso del 5 al 8 de mayo — CALENDARIO EN FIRME
const CICLO_HILO = {
  estado: 'Calendario en firme ✓ — cerrado en reunión del 8 de mayo',
  bajada: 'Fechas, horas y títulos definitivos acordados por Mercy, Jeimmy y Felipe el 8 de mayo de 2026.',
  mensajes: [
    {
      fecha: '2026-05-05', autor: 'mercy', tipo: 'propuesta',
      titulo: 'Propuesta de calendario · 12 sesiones',
      cuerpo: 'Mercy propone arranque el miércoles 13 de mayo con 5 sesiones suyas (finanzas), 5 de Jeimmy (saberes RIJ) y 2 de Felipe (Comunicaciones I y II). Alerta: a Jeimmy le quedan bien los lunes pero mayo y junio tienen lunes festivos.',
    },
    {
      fecha: '2026-05-06', autor: null, tipo: 'observacion',
      titulo: 'Andrea (Fondo Mixto) propone modificar fechas',
      cuerpo: 'Andrea pide ajustar el cronograma para articular el ejercicio inicial. Sus fechas serían 18 y 25 de mayo, 1, 15 y 22 de junio. Queda pendiente reunión para definir.',
    },
    {
      fecha: '2026-05-06', autor: 'mercy', tipo: 'alerta',
      titulo: 'Alerta sobre festivos',
      cuerpo: 'Mercy a Jeimmy: 18 de mayo y 15 de junio son festivos. ¿Quieres ofrecer clases en festivos? Queda atenta a la respuesta.',
    },
    {
      fecha: '2026-05-08', autor: null, tipo: 'cierre',
      titulo: 'Reunión de cierre del 8 de mayo — calendario en firme ✓',
      cuerpo: 'Mercy, Jeimmy y Felipe se reunieron y cerraron el calendario definitivo. Se acordaron 12 sesiones con fechas, horas y títulos exactos. Regla general: lun/mar 18:30–20:00 · vie 17:30–19:00 · si lunes es festivo → martes 10:00–11:30. La sesión inaugural es el lunes 11 de mayo, 18:00–19:30.',
    },
  ],
};

const DOCUMENTOS = [
  {
    id: 'propuesta-ciclo',
    titulo: 'Ciclo de Formación Puente',
    subtitulo: 'Saberes financieros, RIJ y comunicaciones · 12 sesiones',
    autor: 'Mercy · Jeimmy · Felipe',
    fecha: 'Mayo 2026',
    tipo: 'Documento en construcción',
    paginas: 12,
    color: '#5A3680',
    resumen: 'Avanzada formativa del Convenio 1022 con tres líneas que tejen los saberes del equipo: finanzas personales y manejo de recursos (Mercy), saberes RIJ desde lo íntimo, plural y comunitario (Jeimmy) y comunicaciones de las redes (Felipe). Calendario en cierre: mañana en la tarde se consolidan fechas, horas y días con Mercy y Jeimmy.',
    secciones: [
      'Línea finanzas · 5 sesiones · Mercy',
      'Línea RIJ · 5 sesiones · Jeimmy',
      'Línea comunicaciones · 2 sesiones · Felipe',
      'Calendario propuesto · arranca 13 de mayo',
      'Observaciones de Andrea (Fondo Mixto)',
      'Alerta de festivos · 18 de mayo y 15 de junio',
    ],
    enlace: '#ciclo',
  },
  {
    id: 'manual-mujeres',
    titulo: 'Manual de Identidad · Red de Mujeres',
    subtitulo: 'Sistema visual para tejer territorios — v1.0',
    autor: 'Equipo de comunicaciones',
    fecha: 'Abril 2026',
    tipo: 'Manual de identidad',
    paginas: 14,
    color: '#A8438A',
    resumen: 'Marco conceptual, logo, paleta 60·30·10, tres familias tipográficas, patrones de tejido y mola, y aplicaciones del sistema visual de la Red de Mujeres Sabedoras, Artistas y Gestoras.',
    secciones: [
      'Marco conceptual · Cinco principios visuales',
      'Logotipo · Variantes y usos',
      'Color · Paleta principal y secundaria',
      'Tipografía · Display, cuerpo y acento',
      'Patrones · Tejido y mola',
      'Aplicaciones del sistema',
    ],
    enlace: 'uploads/manual_red_mujeres.pptx',
  },
  {
    id: 'manual-rij',
    titulo: 'Manual de Identidad · Red Intercultural Juvenil',
    subtitulo: 'Identidad gráfica de la RIJ',
    autor: 'Equipo de comunicaciones',
    fecha: '2025',
    tipo: 'Manual de identidad',
    paginas: null,
    color: '#D97B3F',
    resumen: 'Sistema gráfico de la Red Intercultural Juvenil. Antecede al manual de la Red de Mujeres y sirvió de modelo para la transferencia de plataforma y kit gráfico.',
    secciones: [
      'Marco conceptual',
      'Logotipo y variantes',
      'Color',
      'Tipografía',
      'Patrones y aplicaciones',
    ],
    enlace: '#',
  },
  {
    id: 'puente',
    titulo: 'Plataforma PUENTE',
    subtitulo: 'En Colombia los puentes cambian vidas',
    autor: 'Equipo Convenio 1022 · 2025',
    fecha: '2025',
    tipo: 'Avanzada conceptual',
    paginas: 9,
    color: '#3D50A8',
    resumen: 'Plataforma de fortalecimiento y agencia de organizaciones en territorio. Avanzada del año pasado que da marco al Convenio 1022: tres rutas (Bastión, Contraventeo, Pasamanos) y cinco enfoques (político, cuidado, investigativo, formativo, administrativo) para que las organizaciones tengan herramientas y agencien sus dinámicas con menos dependencia institucional.',
    secciones: [
      'Apuesta · menos dependencia institucional, más capacidad resolutiva',
      'Cinco enfoques · político, cuidado, investigativo, formativo, administrativo',
      'Ruta Bastión · laboratorios por enfoque',
      'Ruta Contraventeo · formulación, contratación, implementación',
      'Ruta Pasamanos · actividades transversales y soporte',
      'Curva temporal · 4 meses',
    ],
    enlace: 'uploads/presentacion_puente.pdf',
  },
  {
    id: 'cronograma-fuente',
    titulo: 'Cronograma · Mesa del 4 de mayo',
    subtitulo: 'Agenda colectiva de compromisos',
    autor: 'Equipo Convenio 1022',
    fecha: '4 de mayo de 2026',
    tipo: 'Acta de sincronización',
    paginas: null,
    color: '#528E71',
    resumen: 'Compromisos de la primera mesa de sincronización del equipo, base del cronograma vivo de esta bitácora. Cubre del 5 de mayo al 27 de junio de 2026.',
    secciones: [
      '15 fechas clave',
      'Hitos del Ciclo de Formación',
      'Hitos del Encuentro RIJ',
      'Reuniones semanales del equipo',
    ],
    enlace: 'uploads/cronograma_compromisos_convenio_1022.html',
  },
];

// Bitácora — síntesis y novedades
const BITACORA = [
  {
    fecha: '2026-05-11', tipo: 'sintesis', autor: 'felipe',
    titulo: 'Reunión semanal de equipo · 11 de mayo',
    cuerpo: 'Revisión del Ciclo de Formación Puente y logística del Encuentro RIJ. La carta de compromiso operará como inscripción formal. Para Cali (24–27 de junio), se proyectan 50 asistentes en acomodación doble; Yuli gestionará apoyo del British Council para alimentación y Emerson cotizará catering. Se definió invitar a la Red de Hip Hop "como información abierta" a la sesión inaugural. Felipe liderará el branding del encuentro y propondrá una estación de estampado (stencil) en Cali. Jeimmy definirá el espacio para el componente CONPES con Poblaciones.',
  },
  {
    fecha: '2026-05-08', tipo: 'decision', autor: 'yuli',
    titulo: 'Sede del Encuentro RIJ · Cali confirmada',
    cuerpo: 'Al cierre del 8 de mayo, Yuli Camelo nos informó a todas y todos: el Encuentro de la Red Intercultural Juvenil será en Cali. La duda entre Cali y Tunja queda resuelta. Se actualiza el cronograma y se retira la alerta de decisión pendiente.',
  },
  {
    fecha: '2026-05-08', tipo: 'sintesis', autor: 'felipe',
    titulo: 'Acta del 8 de mayo · Ciclo de Formación Puente en firme',
    cuerpo: 'Reunión con Mercy Arias, Jeimmy Ruiz y Felipe Camacho. Decisiones principales: (1) Calendario de 12 sesiones cerrado con fechas, horas y títulos definitivos — arranca el martes 12 de mayo, cierra el lunes 22 de junio; sesión inaugural el lunes 11 de mayo 18:00–19:30. (2) Se certifica a la organización, no a la persona; los representantes pueden rotar entre sesiones. (3) En lugar de formulario de inscripción, se usará carta de compromiso institucional firmada después del 11 de mayo. (4) Tres instrumentos pedagógicos por sesión: autodiagnóstico voluntario de 5 preguntas, lista de asistencia y carta de compromiso. (5) Pendiente: Fondo Mixto confirmar si emite certificación. (6) Las cinco mujeres de la Red de Mujeres quedan invitadas a sesiones de comunicaciones del nodo RIJ mientras se define su continuidad en el Convenio. (7) Minga del Nodo Andina: Felipe se incorpora el 11 de mayo; perfiles ya cerrados desde el 7 de mayo.',
  },
  {
    fecha: '2026-05-07', tipo: 'novedad', autor: 'felipe',
    titulo: 'Ciclo de Formación Puente · entra al sitio en versión propuesta',
    cuerpo: 'Mercy compartió el 5 de mayo una propuesta de 12 sesiones (5 suyas, 5 de Jeimmy, 2 mías). Andrea del Fondo Mixto pidió ajustar fechas y Mercy alertó que el 18 de mayo y el 15 de junio son festivos. Mañana en la tarde nos reunimos las tres para cerrar fechas, horas y días definitivos. Mientras tanto, el calendario queda como propuesta en la sección Ciclo.',
  },
  {
    fecha: '2026-05-07', tipo: 'novedad', autor: 'felipe',
    titulo: 'Estrenamos la Bitácora del equipo',
    cuerpo: 'Este es el primer espacio interno de la Agenda Territorial. Acá vamos a ir consolidando cronograma, tareas y documentos de aquí hasta el cierre del Convenio. Comentarios y ajustes a Felipe.',
  },
  {
    fecha: '2026-05-06', tipo: 'sintesis', autor: 'emerson',
    titulo: 'Avance miércoles',
    cuerpo: 'Jeimmy remitió borrador CONPES Juventudes a Yuli y Mónica. Felipe entregó listado de organizaciones con ubicación a Jeimmy para que pase a Emerson para costeo de transportes.',
  },
  {
    fecha: '2026-05-05', tipo: 'sintesis', autor: 'emerson',
    titulo: 'Mesa de sincronización · cierre',
    cuerpo: 'Reunión con Andrea del Fondo Mixto al mediodía. Quedó aclarada la cláusula que vincula a las organizaciones aliadas y la cláusula octava de derechos de autor. Mercy y Jeimmy firmaron contratos del Ciclo, ajustados a 5 sesiones por orientadora.',
  },
  {
    fecha: '2026-05-04', tipo: 'sintesis', autor: 'yuli',
    titulo: 'Primera mesa de equipo · 4 de mayo',
    cuerpo: 'Definimos cronograma de aquí a junio, fechas tope y responsables. Reunión semanal del equipo queda fijada cada lunes 8:00 a 9:00 a.m. arrancando el 11 de mayo.',
  },
];

const ALERTAS = [
  {
    icono: '!',
    titulo: 'Lunes 11 · Gestión British Council y Fondo Mixto',
    detalle: 'Yuli envía correo para apoyo de alimentación en Cali y precisa emisión de certificados del Ciclo con el gerente del Fondo Mixto.',
    color: '#3D50A8',
  },
  {
    icono: '✓',
    titulo: 'Sede del Encuentro RIJ · Cali confirmada',
    detalle: 'Yuli Camelo informó al equipo al cierre del 8 de mayo: el Encuentro de la RIJ será en Cali.',
    color: '#528E71',
  },
  {
    icono: '✦',
    titulo: 'Próxima reunión semanal · lunes 11, 8:00 a.m.',
    detalle: 'Primer encuentro de seguimiento. Desde acá quedan en agenda recurrente todos los lunes.',
    color: '#3D50A8',
  },
];

// Plataforma PUENTE — avanzada conceptual del año pasado
const PUENTE = {
  lema: 'En Colombia los puentes cambian vidas',
  bajada: 'Plataforma de fortalecimiento y agencia de organizaciones en territorio',
  apuesta: ['Menos dependencia institucional', 'Mayor capacidad resolutiva', 'Pensamiento reflexivo y crítico'],
  enfoques: [
    { n: 'Político', c: '#5A3680' },
    { n: 'Cuidado', c: '#A8438A' },
    { n: 'Investigativo', c: '#3D50A8' },
    { n: 'Formativo', c: '#D97B3F' },
    { n: 'Administrativo', c: '#528E71' },
  ],
  rutas: [
    {
      nombre: 'Bastión',
      bajada: 'Laboratorios por enfoque',
      detalle: 'Autodiagnóstico · derechos culturales · pedagogías sensibles situadas · presupuesto · investigación en procesos artísticos · protocolos de cuidado.',
      color: '#5A3680',
    },
    {
      nombre: 'Contraventeo',
      bajada: 'Formulación, contratación, implementación',
      detalle: 'El puente deja de ser un mecanismo y se vuelve una estructura. Tres etapas: planificación y escritura del proyecto, contratación, acompañamiento + cierre + evaluación.',
      color: '#D97B3F',
    },
    {
      nombre: 'Pasamanos',
      bajada: 'Actividades transversales y soporte',
      detalle: 'Internacionalización · pensamiento estratégico · redes sociales · IA · violencia de género · antimilitarismo · economías populares · finanzas personales. Soporte tecnológico, directorio de saberes, canasto de conocimiento.',
      color: '#528E71',
    },
  ],
  curva: ['Mes 1', 'Mes 2', 'Mes 3 (BIS)', 'Mes 4'],
  cita: '"Ahí está el puente para cruzarlo o para no cruzarlo. Yo lo voy a cruzar, sin prevenciones. En la otra orilla alguien me espera con un durazno y un país."',
  citaAutor: 'Mario Benedetti',
};

window.AGENDA = { TEAM, CRONOGRAMA, CICLO, CICLO_HILO, DOCUMENTOS, BITACORA, ALERTAS, HOY_ISO, PUENTE };
